# Generated by Django 5.0.6 on 2026-09-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0021_supplierinvoiceline_po_line_and_more'),
        ('procurement', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0004_property_management_fee_rate_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='projects.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='property_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='expense_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxcode'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='procurement.purchaseorderline'),
        ),
    ]
