# Generated by Django 5.0.6 on 2026-10-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0005_assetcategory_default_useful_life_months_and_more'),
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='fixed_assets.assetcategory'),
        ),
    ]
