# Generated by Django 6.0.3 on 2026-04-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_journalentry_batch'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='COGS or Expense account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_expense', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Revenue account for sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_income', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Asset account for stock on hand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_inventory', to='finance.chartofaccount'),
        ),
    ]
