# Generated by Django 5.0.6 on 2026-03-12 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('rentals', '0003_alter_lease_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='core.currency'),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_invoices', to='core.currency'),
        ),
    ]
