# Generated by Django 5.0.6 on 2026-03-16 17:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_maintenancerequest_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='amount_from_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount deducted from tenant credit balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalpayment',
            name='withholding_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax deducted by tenant', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rentalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Cash/Bank amount received', max_digits=10),
        ),
    ]
