# Generated by Django 5.0.6 on 2026-03-24 20:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recurring fixed bonus', max_digits=12),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recurring fixed deductions (e.g. medical)', max_digits=12),
        ),
    ]
