# Generated by Django 6.0.3 on 2026-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_employee_basic_salary_remove_employee_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_departments',
            field=models.ManyToManyField(blank=True, related_name='secondary_employees', to='hr.department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_positions',
            field=models.ManyToManyField(blank=True, related_name='secondary_employees', to='hr.jobposition'),
        ),
    ]
