# Generated by Django 5.0.6 on 2026-10-09 06:13

from django.db import migrations, models
from django.db.models import Q


def classify(apps, schema_editor):
    """Agents: commission-only staff or anyone with a Fidelity Fund registration. Managers: whoever
    already manages a department or has people reporting to them. Then reporting lines follow departments."""
    Employee = apps.get_model('hr', 'Employee')
    Department = apps.get_model('hr', 'Department')
    Employee.objects.filter(Q(employment_type='commission_only') | Q(principal_agent=True)
                            | ~Q(fidelity_fund_number='')).update(staff_type='agent')
    managers = set(Department.objects.exclude(manager=None).values_list('manager_id', flat=True)) \
        | set(Employee.objects.exclude(reports_to=None).values_list('reports_to_id', flat=True))
    Employee.objects.filter(pk__in=managers).update(is_manager=True)
    for dept in Department.objects.exclude(manager=None):
        Employee.objects.filter(department=dept).exclude(pk=dept.manager_id).update(reports_to_id=dept.manager_id)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_employee_basic_salary_remove_employee_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_type',
            field=models.CharField(choices=[('employee', 'Company employee'), ('agent', 'Agent')], default='employee', max_length=10),
        ),
        migrations.RunPython(classify, migrations.RunPython.noop),
    ]
