# Generated by Django 5.0.6 on 2026-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_staff_type_manager_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveallocation',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('special', 'Special Leave'), ('family', 'Family Responsibility'), ('maternity', 'Maternity Leave'), ('study', 'Study Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('special', 'Special Leave'), ('family', 'Family Responsibility'), ('maternity', 'Maternity Leave'), ('study', 'Study Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
    ]
