# Generated by Django 5.0.6 on 2026-09-30 09:20

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0021_supplierinvoiceline_po_line_and_more'),
        ('fixed_assets', '0004_assetbook_posts_to_gl'),
        ('properties', '0004_property_management_fee_rate_property_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'In progress'), ('completed', 'Completed (capitalised)'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('capitalise_to', models.CharField(choices=[('inventory', 'Property inventory (for sale)'), ('fixed_asset', 'Fixed asset (held / investment)')], default='inventory', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cost_center', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project', to='finance.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('wip_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wip_projects', to='finance.chartofaccount')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCapitalisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capitalisation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('target', models.CharField(choices=[('inventory', 'Property inventory (for sale)'), ('fixed_asset', 'Fixed asset (held / investment)')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fixed_assets.fixedasset')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.journalentry')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capitalisations', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_capitalisations',
                'ordering': ['-capitalisation_date'],
            },
        ),
    ]
