# Generated by Django 5.0.6 on 2026-03-16 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_exchangerate_options_and_more'),
        ('payroll', '0004_payrollsetting_taxbracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to='finance.supplierinvoice'),
        ),
    ]
