# Generated by Django 5.0.6 on 2026-10-02 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0009_contact_bank_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('logged', 'Logged only (no SMS gateway configured)'), ('failed', 'Failed'), ('skipped', 'Skipped (no address)')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. rent_reminder, arrears, bulk', max_length=50)),
                ('related_object', models.CharField(blank=True, help_text='e.g. lease:LSE-00012', max_length=100)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='crm.contact')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='notificatio_categor_24e37a_idx'), models.Index(fields=['contact', 'created_at'], name='notificatio_contact_176fc1_idx')],
            },
        ),
    ]
