# Generated by Django 5.0.6 on 2026-10-08 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('level', models.CharField(choices=[('info', 'Information'), ('action', 'Action needed'), ('warning', 'Warning')], default='info', max_length=10)),
                ('category', models.CharField(blank=True, help_text='e.g. batch_approval, leave_request', max_length=50)),
                ('related_object', models.CharField(blank=True, max_length=100)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_inbox',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='notificatio_recipie_e9ec0f_idx')],
            },
        ),
    ]
