# Generated by Django 5.0.6 on 2026-03-04 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commissions', '0001_initial'),
        ('finance', '0001_initial'),
        ('hr', '0001_initial'),
        ('properties', '0001_initial'),
        ('rentals', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.lease'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='sale_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.saletransaction'),
        ),
        migrations.AddField(
            model_name='commissionrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
