# Generated by Django 5.0.6 on 2026-03-24 17:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionstructure',
            name='agent_split',
        ),
        migrations.RemoveField(
            model_name='commissionstructure',
            name='company_rate',
        ),
        migrations.RemoveField(
            model_name='commissionstructure',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base % rate', max_digits=5),
        ),
        migrations.AddField(
            model_name='commissionstructure',
            name='calculation_type',
            field=models.CharField(choices=[('standard', 'Standard Flat Rate'), ('tiered', 'Tiered Target')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='commissions.commissionstructure')),
            ],
            options={
                'db_table': 'commission_tiers',
                'ordering': ['threshold_amount'],
            },
        ),
    ]
