# Generated by Django 6.0.3 on 2026-04-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_remove_commissionstructure_agent_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionrecord',
            name='agent_role',
            field=models.CharField(choices=[('listing', 'Listing'), ('selling', 'Selling'), ('single', 'Single Agent')], default='single', help_text='Role played by the agent in this specific transaction.', max_length=20),
        ),
    ]
