# Generated by Django 5.0.6 on 2026-03-10 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Customer Invoice'", max_length=100, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveIntegerField(default=4, help_text='Number of digits, e.g. 4 for 0001')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
                'db_table': 'core_number_sequences',
            },
        ),
    ]
