# Generated by Django 5.0.6 on 2026-09-30 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('crm', '0007_contact_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('finance_manager', 'Finance Manager'), ('sales_manager', 'Sales Manager'), ('rental_manager', 'Rental Manager'), ('agent', 'Property Agent'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('compliance_officer', 'Compliance Officer'), ('executive', 'Executive / Director'), ('viewer', 'Read-Only Viewer'), ('tenant', 'Tenant (self-service portal)')], max_length=50, unique=True),
        ),
    ]
