# Generated by Django 5.0.6 on 2026-10-02 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_contact_alter_role_role_type'),
        ('finance', '0022_bankaccount_default_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_user', to='finance.supplier'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('finance_manager', 'Finance Manager'), ('sales_manager', 'Sales Manager'), ('rental_manager', 'Rental Manager'), ('agent', 'Property Agent'), ('accountant', 'Accountant'), ('hr_manager', 'HR Manager'), ('compliance_officer', 'Compliance Officer'), ('executive', 'Executive / Director'), ('viewer', 'Read-Only Viewer'), ('tenant', 'Tenant (self-service portal)'), ('owner', 'Property owner (owner portal)'), ('contractor', 'Contractor (contractor portal)')], max_length=50, unique=True),
        ),
    ]
