# Generated by Django 5.0.6 on 2026-03-12 12:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetbook',
            name='consumed_units',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='assetbook',
            name='total_expected_units',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
