# Generated by Django 5.0.6 on 2026-10-08 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_posting_profile_property_accounts'),
        ('fixed_assets', '0004_assetbook_posts_to_gl'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='default_useful_life_months',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='purchase_invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_assets', to='finance.supplierinvoiceline'),
        ),
    ]
