# Generated by Django 5.0.6 on 2026-03-13 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'core_modules',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_approve_commissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_crm',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_finance',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_hr',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_edit_properties',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_manage_documents',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_post_journal',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_commissions',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_crm',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_dashboard',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_documents',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_executive_dashboard',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_finance',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_hr',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_properties',
        ),
        migrations.AddField(
            model_name='role',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.module'),
        ),
        migrations.CreateModel(
            name='SODRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('critical', 'Critical (Hard Block)'), ('warning', 'Warning (Soft Block)'), ('advisory', 'Advisory')], default='critical', max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('module_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sod_conflicts_a', to='core.module')),
                ('module_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sod_conflicts_b', to='core.module')),
            ],
            options={
                'db_table': 'core_sod_rules',
            },
        ),
        migrations.AddConstraint(
            model_name='sodrule',
            constraint=models.UniqueConstraint(fields=('module_a', 'module_b'), name='unique_sod_pair'),
        ),
    ]
