# Generated by Django 5.0.6 on 2026-03-16 12:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollrun_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payrollitem',
            old_name='deductions',
            new_name='other_deductions',
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='aids_levy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='3% of PAYE', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='nssa_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='NSSA Pension', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='PAYE', max_digits=12),
        ),
    ]
