# Generated by Django 6.0.3 on 2026-03-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payslip_salaryrule_payslipline_salarystructure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollItem',
        ),
    ]
