# Generated by Django 6.0.3 on 2026-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_delete_payrollitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='bank_account_snapshot',
            field=models.CharField(blank=True, help_text='Snapshot of bank details at time of processing', max_length=255),
        ),
    ]
