# Generated by Django 6.0.3 on 2026-03-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_postingprofile_commission_expense_and_more'),
        ('payroll', '0008_payslip_bank_account_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrule',
            name='credit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_rule_credits', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='salaryrule',
            name='debit_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_rule_debits', to='finance.chartofaccount'),
        ),
    ]
