# Generated by Django 5.0.6 on 2026-09-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_add_rule_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrule',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('net', 'Net'), ('employer', 'Employer Contribution')], max_length=20),
        ),
    ]
