# Generated by Django 6.0.3 on 2026-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_add_rule_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrule',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('allowance', 'Allowance'), ('deduction', 'Deduction'), ('contribution', 'Employer Contribution'), ('net', 'Net')], max_length=20),
        ),
    ]
