# Generated by Django 5.0.6 on 2026-03-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_journalentry_currency_journalentry_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
