# Generated by Django 5.0.6 on 2026-03-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_journalline_employee_ref_journalline_supplier_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='allow_manual_entry',
            field=models.BooleanField(default=True, help_text='Whether this account can be used in manual journal entries'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='allowed_transaction_types',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed JournalEntry types (e.g. ["manual", "sales"]). Empty means all are allowed.'),
        ),
    ]
