# Generated by Django 5.0.6 on 2026-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('posted', 'Posted / Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid in Full'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
