# Generated by Django 5.0.6 on 2026-03-24 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_supplierinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingprofile',
            name='commission_expense',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='comm_exp_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='cost_of_sales',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cos_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='property_inventory',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inv_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='sale_revenue',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'revenue'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sale_rev_profiles', to='finance.chartofaccount'),
        ),
    ]
