# Generated by Django 6.0.3 on 2026-04-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_journalbatch_journalentry_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.journalbatch'),
        ),
    ]
