# Generated by Django 5.0.6 on 2026-09-30 07:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def open_legacy_supplier_payments(apps, schema_editor):
    """
    Before settlement existed, posting a supplier payment never touched any
    invoice, so every posted payment is still fully unapplied. Customer
    receipts were applied oldest-first at posting, so they stay at 0.
    """
    SupplierPayment = apps.get_model('finance', 'SupplierPayment')
    SupplierPayment.objects.filter(status='posted').update(unapplied_amount=models.F('amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_journalbatch_journalentry_batch'),
        ('properties', '0003_property_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='requires_cost_center',
            field=models.BooleanField(default=False, help_text='Postings to this account must carry a cost center (dimension).'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='finance.customerinvoice'),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='customerinvoiceline',
            name='property_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='unapplied_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='auto_reverse_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.costcenter'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='property_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='unapplied_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='APAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payment', 'Receipt / payment applied'), ('credit_note', 'Credit note applied'), ('write_off', 'Written off'), ('refund', 'Credit refunded')], max_length=20)),
                ('allocation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fx_difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_allocations', to='finance.supplierinvoice')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.supplierinvoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.journalentry')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.supplierpayment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_ap_allocations',
                'ordering': ['allocation_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ARAllocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('payment', 'Receipt / payment applied'), ('credit_note', 'Credit note applied'), ('write_off', 'Written off'), ('refund', 'Credit refunded')], max_length=20)),
                ('allocation_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fx_difference', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_allocations', to='finance.customerinvoice')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.customerinvoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.journalentry')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.customerreceipt')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_ar_allocations',
                'ordering': ['allocation_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_run_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_post', models.BooleanField(default=False)),
                ('reverse_next_period', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journal')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_recurring_journals',
                'ordering': ['next_run_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.costcenter')),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.recurringjournal')),
            ],
            options={
                'db_table': 'finance_recurring_journal_lines',
            },
        ),
        migrations.RunPython(open_legacy_supplier_payments, migrations.RunPython.noop),
    ]
