# Generated by Django 5.0.6 on 2026-09-30 07:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('finance', '0016_settlement_fx_dimensions_recurring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('document_type', models.CharField(choices=[('supplier_invoice', 'Supplier invoice / credit note'), ('supplier_payment', 'Supplier payment')], max_length=30)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sequence', models.PositiveSmallIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_rules', to='core.role')),
            ],
            options={
                'db_table': 'finance_approval_rules',
                'ordering': ['document_type', 'sequence', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('supplier_invoice', 'Supplier invoice / credit note'), ('supplier_payment', 'Supplier payment')], max_length=30)),
                ('object_id', models.UUIDField(db_index=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.approvalrule')),
            ],
            options={
                'db_table': 'finance_approval_records',
                'ordering': ['created_at'],
            },
        ),
    ]
