# Generated by Django 5.0.6 on 2026-09-30 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_supplierinvoice_match_override_by_and_more'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoiceline',
            name='po_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='procurement.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='approvalrecord',
            name='document_type',
            field=models.CharField(choices=[('supplier_invoice', 'Supplier invoice / credit note'), ('supplier_payment', 'Supplier payment'), ('purchase_order', 'Purchase order')], max_length=30),
        ),
        migrations.AlterField(
            model_name='approvalrule',
            name='document_type',
            field=models.CharField(choices=[('supplier_invoice', 'Supplier invoice / credit note'), ('supplier_payment', 'Supplier payment'), ('purchase_order', 'Purchase order')], max_length=30),
        ),
    ]
