# Generated by Django 5.0.6 on 2026-09-30 14:41

import apps.finance.models.bank
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_contact_alter_role_role_type'),
        ('finance', '0021_supplierinvoiceline_po_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(db_column='currency', default=apps.finance.models.bank.default_currency_code, on_delete=django.db.models.deletion.PROTECT, to='core.currency', to_field='code'),
        ),
    ]
