# Generated by Django 5.0.6 on 2026-10-08 11:22

import django.db.models.deletion
from django.db import migrations, models

# The codes these postings used before they were configurable.
PREVIOUS_CODES = {
    'owner_funds': '2210',
    'management_fees': '4300',
    'recoveries_income': '4920',
    'maintenance': '5300',
    'withholding_tax': '1120',
}


def fill_existing_profiles(apps, schema_editor):
    """Point existing profiles at the accounts the code used to hard-wire, so nothing changes on upgrade."""
    PostingProfile = apps.get_model('finance', 'PostingProfile')
    ChartOfAccount = apps.get_model('finance', 'ChartOfAccount')
    accounts = {a.code: a for a in ChartOfAccount.objects.filter(code__in=PREVIOUS_CODES.values())}
    for profile in PostingProfile.objects.all():
        changed = []
        for field, code in PREVIOUS_CODES.items():
            if getattr(profile, f'{field}_id') is None and code in accounts:
                setattr(profile, field, accounts[code])
                changed.append(field)
        if changed:
            profile.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_bankaccount_default_base_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingprofile',
            name='maintenance',
            field=models.ForeignKey(blank=True, help_text='Maintenance and repairs on company-owned property (starter chart: 5300).', limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='maintenance_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='management_fees',
            field=models.ForeignKey(blank=True, help_text='Management, letting and agency fee income (starter chart: 4300).', limit_choices_to={'account_type': 'revenue'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mgmt_fee_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='owner_funds',
            field=models.ForeignKey(blank=True, help_text='Trust liability for money held for property owners (starter chart: 2210).', limit_choices_to={'account_type': 'liability'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='owner_funds_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='recoveries_income',
            field=models.ForeignKey(blank=True, help_text='Recharges to tenants: utilities, recoveries, damages (starter chart: 4920).', limit_choices_to={'account_type': 'revenue'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recoveries_profiles', to='finance.chartofaccount'),
        ),
        migrations.AddField(
            model_name='postingprofile',
            name='withholding_tax',
            field=models.ForeignKey(blank=True, help_text='Tax withheld by tenants and claimable (starter chart: 1120).', limit_choices_to={'account_type': 'asset'}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='wht_profiles', to='finance.chartofaccount'),
        ),
        migrations.RunPython(fill_existing_profiles, migrations.RunPython.noop),
    ]
