# Generated by Django 5.0.6 on 2026-03-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'properties_types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('ownership_type', models.CharField(choices=[('owned', 'Company Owned'), ('managed', 'Managed (Third Party)'), ('jv', 'Joint Venture')], default='owned', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('under_contract', 'Under Contract'), ('maintenance', 'Under Maintenance'), ('listed_sale', 'Listed for Sale'), ('listed_rent', 'Listed for Rent'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='available', max_length=30)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='South Africa', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('erf_size', models.DecimalField(blank=True, decimal_places=2, help_text='Erf size in m²', max_digits=12, null=True)),
                ('floor_size', models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in m²', max_digits=12, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('garages', models.PositiveSmallIntegerField(default=0)),
                ('parking_bays', models.PositiveSmallIntegerField(default=0)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('current_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_valuation_date', models.DateField(blank=True, null=True)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rental_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly rental rate', max_digits=12, null=True)),
                ('rates_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('levies_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bond_institution', models.CharField(blank=True, max_length=100)),
                ('bond_monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gl_account_code', models.CharField(blank=True, help_text='Chart of accounts reference', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature strings')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('primary_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_properties', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype')),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['reference_number'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='properties/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('exterior', 'Exterior'), ('interior', 'Interior'), ('floor_plan', 'Floor Plan'), ('aerial', 'Aerial'), ('other', 'Other')], default='interior', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'properties_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('floor_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('monthly_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties_units',
            },
        ),
        migrations.CreateModel(
            name='PropertyInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_type', models.CharField(choices=[('ingoing', 'Ingoing Inspection'), ('outgoing', 'Outgoing Inspection'), ('routine', 'Routine Inspection'), ('maintenance', 'Maintenance Inspection')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('condition_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-10 rating', null=True)),
                ('findings', models.TextField(blank=True)),
                ('action_required', models.TextField(blank=True)),
                ('report_document', models.FileField(blank=True, null=True, upload_to='inspections/%Y/%m/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyunit')),
            ],
            options={
                'db_table': 'properties_inspections',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_date', models.DateField()),
                ('valuation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valuator_name', models.CharField(max_length=200)),
                ('valuator_company', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(blank=True, help_text='Valuation method used', max_length=100)),
                ('report_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties_valuations',
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties_status_e6008a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'suburb'], name='properties_city_087dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties_propert_f6c75f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyunit',
            unique_together={('property', 'unit_number')},
        ),
    ]
