# Generated by Django 5.0.6 on 2026-03-12 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('properties', '0002_alter_property_city_alter_property_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.currency'),
        ),
    ]
