# Generated by Django 5.0.6 on 2026-09-30 07:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contact_last_activity_at_and_more'),
        ('properties', '0003_property_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='management_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='% of rent retained as management fee (managed properties)', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Landlord, for managed properties', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_properties', to='crm.contact'),
        ),
    ]
