# Generated by Django 6.0.3 on 2026-04-07 09:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('hr', '0004_remove_employee_basic_salary_remove_employee_bonus_and_more'),
        ('properties', '0004_alter_property_asking_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boreholes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='built_in_cupboards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='carports',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='cottage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='cottage_bathrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='cottage_beds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='cottage_dining',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='cottage_parking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='dining_rooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='entertainment_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.UUIDField(blank=True, help_text='Original ID from website/Supabase', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fitted_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='landscaped_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lounges',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='mes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='storeys',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='tiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='walled_fenced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='website_category',
            field=models.CharField(blank=True, choices=[('for-sale', 'For Sale'), ('for-rent', 'For Rent'), ('auctions', 'Auctions')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='properties_slug_e22d01_idx'),
        ),
    ]
