# Generated by Django 5.0.6 on 2026-10-02 10:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_custom_fields'),
        ('properties', '0004_property_management_fee_rate_property_owner'),
        ('rentals', '0010_lease_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'properties_portfolios',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='rentals.lease'),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='unit_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('office', 'Office'), ('retail', 'Retail / Shop'), ('industrial', 'Industrial / Warehouse'), ('parking', 'Parking'), ('storage', 'Storage'), ('other', 'Other')], default='residential', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='floor_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross lettable area (m²)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertyunit',
            name='monthly_rental',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Asking (market) rent', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('property', 'Property'), ('unit', 'Unit'), ('lease', 'Lease'), ('contact', 'Contact')], max_length=20)),
                ('key', models.SlugField(help_text='Stored name, e.g. "erf_number"', max_length=60)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Yes / No'), ('choice', 'Choice')], default='text', max_length=10)),
                ('choices', models.JSONField(blank=True, default=list, help_text='Options for a choice field')),
                ('required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'properties_custom_fields',
                'ordering': ['entity', 'sort_order', 'label'],
                'unique_together': {('entity', 'key')},
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='e.g. Kitchen, Bedroom 1', max_length=100)),
                ('item', models.CharField(help_text='e.g. Walls, Stove, Windows', max_length=150)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged'), ('missing', 'Missing'), ('na', 'Not applicable')], default='good', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspections/photos/%Y/%m/')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='properties.propertyinspection')),
            ],
            options={
                'db_table': 'properties_inspection_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.portfolio'),
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='property_shares', to='crm.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='properties.property')),
            ],
            options={
                'db_table': 'properties_ownerships',
                'unique_together': {('property', 'owner')},
            },
        ),
    ]
