# Generated by Django 6.0.3 on 2026-04-07 10:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contact_last_activity_at_and_more'),
        ('properties', '0005_property_boreholes_property_built_in_cupboards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='insurance_monthly',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The third-party owner of the property (for managed units).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='crm.contact'),
        ),
    ]
