# Generated by Django 5.0.6 on 2026-10-02 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_portfolio_property_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='letting_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="% of the first month's rent, charged when a new lease starts", max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='procurement_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% of maintenance cost charged for arranging the work', max_digits=5),
        ),
    ]
