# Generated by Django 5.0.6 on 2026-10-08 11:18

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_letting_fee_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default=apps.properties.models.default_country, max_length=50),
        ),
    ]
