# Generated by Django 6.0.3 on 2026-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_insurance_monthly_property_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyinspection',
            options={'ordering': ['-inspection_date']},
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='condition_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyinspection',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='propertyinspection',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
