# Generated by Django 5.0.6 on 2026-10-08 11:26

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_country_defaults_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='management_fee_rate',
            field=models.DecimalField(decimal_places=2, default=apps.properties.models.default_management_fee_rate, help_text='% of rent retained as management fee (managed properties)', max_digits=5),
        ),
    ]
