# Generated by Django 5.0.6 on 2026-03-12 13:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_currency'),
        ('documents', '0001_initial'),
        ('finance', '0009_postingprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Internal identifier (e.g., FNB-OPER-01)', max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=11, null=True)),
                ('account_type', models.CharField(choices=[('current', 'Current/Checking'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('loan', 'Loan Account'), ('investment', 'Investment')], default='current', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_bank_accounts', to='finance.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CorporateBankStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100)),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reconciling', 'Reconciling'), ('reconciled', 'Reconciled')], default='draft', max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banking.corporatebankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporateBankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('journal_entry_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalline')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banking.corporatebankstatement')),
            ],
        ),
    ]
