# Generated by Django 5.0.6 on 2026-03-11 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('rentals', '0002_maintenancerequest_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='crm.contact'),
        ),
    ]
