# Generated by Django 5.0.6 on 2026-03-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('rentals', '0004_lease_currency_rentalinvoice_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_requests', to='core.currency'),
        ),
    ]
