# Generated by Django 6.0.3 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_rentalpayment_amount_from_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='last_escalation_date',
            field=models.DateField(blank=True, help_text='Most recent date an annual rent increase was applied', null=True),
        ),
    ]
