# Generated by Django 6.0.3 on 2026-04-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_lease_last_escalation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='previous_lease',
            field=models.ForeignKey(blank=True, help_text='The preceding lease that this agreement replaces.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_leases', to='rentals.lease'),
        ),
    ]
