# Generated by Django 5.0.6 on 2026-09-30 07:34

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_settlement_fx_dimensions_recurring'),
        ('rentals', '0007_lease_last_escalation_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_jobs', to='finance.supplier'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='recharge_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_recharges', to='finance.customerinvoice'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='supplier_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='charges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='credited_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rentalinvoice',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of `charges`, including their VAT', max_digits=10),
        ),
        migrations.CreateModel(
            name='LeaseCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_type', models.CharField(choices=[('service_charge', 'Service Charge / Levy'), ('utilities', 'Utilities Recovery'), ('parking', 'Parking'), ('insurance', 'Insurance Recovery'), ('other', 'Other')], default='service_charge', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_applicable', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='rentals.lease')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rentals_lease_charges',
                'ordering': ['lease', 'charge_type'],
            },
        ),
    ]
