# Generated by Django 5.0.6 on 2026-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_maintenancerequest_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='payment_method',
            field=models.CharField(choices=[('eft', 'EFT / Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('debit_order', 'Debit Order'), ('credit_card', 'Credit Card'), ('online', 'Online (tenant portal)')], max_length=20),
        ),
    ]
