# Generated by Django 5.0.6 on 2026-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_rentalpayment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
