# Generated by Django 6.0.3 on 2026-04-07 10:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('crm', '0007_contact_last_activity_at_and_more'),
        ('finance', '0016_alter_journalentry_batch'),
        ('properties', '0006_property_insurance_monthly_property_owner'),
        ('rentals', '0009_rentalinvoice_electricity_charges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='management_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Monthly management fee % deducted from rent', max_digits=5),
        ),
        migrations.CreateModel(
            name='OwnerSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_rent_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('management_fee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expenses_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payout_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='crm.contact')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rentals_owner_settlements',
                'ordering': ['-period_start'],
            },
        ),
    ]
