# Generated by Django 5.0.6 on 2026-10-02 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_lease_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='cpi_margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='% added to CPI growth for CPI-linked escalation', max_digits=5),
        ),
        migrations.AddField(
            model_name='lease',
            name='escalation_type',
            field=models.CharField(choices=[('fixed', 'Fixed annual %'), ('stepped', 'Stepped schedule'), ('cpi', 'CPI-linked'), ('none', 'No escalation')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='letting_fee_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_provider',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='signature_status',
            field=models.CharField(choices=[('not_sent', 'Not sent'), ('sent', 'Sent for signature'), ('signed', 'Signed'), ('declined', 'Declined')], default='not_sent', max_length=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='turnover_rent_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
