# Generated by Django 5.0.6 on 2026-10-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_posting_profile_property_accounts'),
        ('rentals', '0011_lease_cpi_margin_lease_escalation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_payments', to='finance.bankaccount'),
        ),
    ]
