# Generated by Django 5.0.6 on 2026-10-08 11:26

import apps.rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_rental_payment_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='rental_escalation_rate',
            field=models.DecimalField(decimal_places=2, default=apps.rentals.models.default_escalation_rate, help_text='Annual escalation % (default: Property settings > Defaults)', max_digits=5),
        ),
    ]
