# Generated by Django 5.0.6 on 2026-03-04 15:13

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('rental', 'Rental')], max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company_commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agent_split_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_commission', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='calculated', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'commission_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('rental', 'Rental'), ('commercial', 'Commercial')], max_length=20)),
                ('company_rate', models.DecimalField(decimal_places=2, help_text='% of sale/rental price', max_digits=5)),
                ('agent_split', models.DecimalField(decimal_places=2, help_text='% of company commission to agent', max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'commission_structures',
            },
        ),
    ]
