# Generated by Django 5.0.6 on 2026-09-30 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_user_contact_alter_role_role_type'),
        ('crm', '0007_contact_last_activity_at_and_more'),
        ('finance', '0021_supplierinvoiceline_po_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocations', models.JSONField(default=list)),
                ('gateway', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed / cancelled')], default='created', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('redirect_url', models.URLField(blank=True, max_length=500)),
                ('poll_url', models.URLField(blank=True, max_length=500)),
                ('gateway_status', models.CharField(blank=True, max_length=50)),
                ('receipted', models.BooleanField(default=False)),
                ('receipt_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='crm.contact')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='finance.customerprofile')),
            ],
            options={
                'db_table': 'portal_online_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
