# Generated by Django 5.0.6 on 2026-03-04 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('pipeline_type', models.CharField(choices=[('sale', 'Sales'), ('rental', 'Rental'), ('general', 'General')], default='sale', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'crm_pipelines',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone_mobile', models.CharField(blank=True, max_length=20)),
                ('phone_work', models.CharField(blank=True, max_length=20)),
                ('phone_home', models.CharField(blank=True, max_length=20)),
                ('contact_type', models.CharField(choices=[('lead', 'Lead'), ('prospect', 'Prospect'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('investor', 'Investor'), ('attorney', 'Attorney'), ('bank', 'Bank / Financier'), ('other', 'Other')], default='lead', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('rating', models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, help_text='How did they find us?', max_length=100)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('suburb', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('credit_rating', models.CharField(blank=True, max_length=10)),
                ('affordability', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('preferred_areas', models.JSONField(blank=True, default=list)),
                ('property_preferences', models.JSONField(blank=True, default=dict)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='contacts/avatars/')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='hr.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contacts',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('lost_reason', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='hr.employee')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline')),
            ],
            options={
                'db_table': 'crm_opportunities',
                'ordering': ['stage__position', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('viewing', 'Property Viewing'), ('task', 'Task'), ('note', 'Note'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='planned', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.contact')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity')),
            ],
            options={
                'db_table': 'crm_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('stage_type', models.CharField(choices=[('initial', 'Initial Contact'), ('qualified', 'Qualified'), ('viewing', 'Viewing Scheduled'), ('offer', 'Offer Submitted'), ('negotiation', 'In Negotiation'), ('accepted', 'Offer Accepted'), ('due_diligence', 'Due Diligence'), ('documentation', 'Documentation'), ('closing', 'Closing'), ('won', 'Won / Closed'), ('lost', 'Lost')], max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(default='#E5A645', max_length=7)),
                ('probability', models.PositiveSmallIntegerField(default=0, help_text='% probability of closing')),
                ('is_terminal', models.BooleanField(default=False, help_text='Won or Lost stage')),
                ('is_won', models.BooleanField(default=False)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline')),
            ],
            options={
                'db_table': 'crm_pipeline_stages',
                'ordering': ['pipeline', 'position'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type', 'status'], name='crm_contact_contact_418037_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['assigned_agent'], name='crm_contact_assigne_f98e82_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['stage', 'position'], name='crm_opportu_stage_i_3cde8e_idx'),
        ),
    ]
