# Generated by Django 5.0.6 on 2026-10-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'document categories'},
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
