# Generated by Django 5.0.6 on 2026-03-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact_currency_opportunity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='guarantor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='guarantor_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
