# Generated by Django 6.0.3 on 2026-03-28 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_contact_guarantor_email_contact_guarantor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrmTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#E5A645', help_text='Hex color for UI badge', max_length=7)),
            ],
            options={
                'db_table': 'crm_tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['stage__position', 'position'], 'verbose_name_plural': 'opportunities'},
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='expected_close_date',
            new_name='expected_closing',
        ),
        migrations.RenameField(
            model_name='opportunity',
            old_name='expected_value',
            new_name='expected_revenue',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='property',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='notes',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='email_from',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_lead',
            field=models.BooleanField(default=True, help_text='False once converted to an Opportunity'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=200),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(choices=[('0', 'Low'), ('1', 'Medium'), ('2', 'High'), ('3', 'Very High')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(help_text='Lead or Opportunity title', max_length=200),
        ),
        migrations.AlterField(
            model_name='pipelinestage',
            name='stage_type',
            field=models.CharField(choices=[('initial', 'Initial Contact / Lead'), ('qualified', 'Qualified'), ('viewing', 'Viewing Scheduled'), ('offer', 'Offer Submitted'), ('negotiation', 'In Negotiation'), ('accepted', 'Offer Accepted'), ('due_diligence', 'Due Diligence'), ('documentation', 'Documentation'), ('closing', 'Closing'), ('won', 'Won / Closed'), ('lost', 'Lost')], max_length=20),
        ),
        migrations.CreateModel(
            name='CrmNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='crm/attachments/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.opportunity')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='opportunities', to='crm.crmtag'),
        ),
    ]
