# Generated by Django 6.0.3 on 2026-03-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_crmtag_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_activities', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='crmnote',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='crm.contact'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_activities', to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='crmnote',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_notes', to='crm.opportunity'),
        ),
    ]
