# Generated by Django 6.0.3 on 2026-03-29 18:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('crm', '0005_activity_contact_crmnote_contact_and_more'),
        ('hr', '0002_employee_bonus_employee_other_deductions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'crm_email_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'crm_lost_reasons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry / Sector', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lead score 0-100 based on activity and profile completeness'),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='contact',
            name='website',
            field=models.URLField(blank=True, help_text='Company or personal website'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason_text',
            field=models.CharField(blank=True, help_text='Free-text override or additional notes on loss reason', max_length=300),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='crm_contact_email_75ee32_idx'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lost_reason',
            field=models.ForeignKey(blank=True, help_text='Normalised reason why deal was lost', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lostreason'),
        ),
    ]
