# Generated by Django 6.0.3 on 2026-03-29 22:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_add_lost_reason_email_template_enrichment'),
        ('hr', '0002_employee_bonus_employee_other_deductions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='stage_entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='sla_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Maximum days a deal should stay in this stage before alert'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_opportunities', to='crm.contact'),
        ),
        migrations.CreateModel(
            name='ContactDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., ID Copy, Proof of Residence', max_length=200)),
                ('document_type', models.CharField(choices=[('id', 'ID / Passport'), ('residence', 'Proof of Residence'), ('tax', 'Tax Clearance'), ('contract', 'Signed Contract'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='crm/documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_crm_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_contact_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(blank=True, related_name='sales_teams', to='hr.employee')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='hr.employee')),
            ],
            options={
                'db_table': 'crm_sales_teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.salesteam'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sales_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.salesteam'),
        ),
    ]
