# Generated by Django 6.0.3 on 2026-04-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_contact_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_account_type',
            field=models.CharField(choices=[('current', 'Current / Cheque'), ('savings', 'Savings'), ('corporate', 'Corporate')], default='current', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for payouts', max_length=100),
        ),
    ]
