# Generated by Django 5.0.6 on 2026-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_contact_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
