# Generated by Django 5.0.6 on 2026-03-04 15:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0001_initial'),
        ('hr', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deposit_due_date', models.DateField(blank=True, null=True)),
                ('deposit_paid_date', models.DateField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('7.00'), help_text='% commission', max_digits=5)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bond_required', models.BooleanField(default=True)),
                ('bond_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bond_institution', models.CharField(blank=True, max_length=100)),
                ('bond_approved_date', models.DateField(blank=True, null=True)),
                ('bond_granted', models.BooleanField(blank=True, null=True)),
                ('offer_date', models.DateField()),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('occupation_date', models.DateField(blank=True, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('transferring_attorney', models.CharField(blank=True, max_length=200)),
                ('bond_attorney', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('offer_submitted', 'Offer Submitted'), ('offer_accepted', 'Offer Accepted'), ('suspensive', 'Suspensive Conditions'), ('bond_approved', 'Bond Approved'), ('transfer', 'Transfer in Progress'), ('registered', 'Registered / Complete'), ('cancelled', 'Cancelled / Fallen Through')], default='offer_submitted', max_length=30)),
                ('is_posted_to_finance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('listing_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_sales', to='hr.employee')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.opportunity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='properties.property')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.contact')),
                ('selling_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selling_sales', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_transactions',
                'ordering': ['-offer_date'],
            },
        ),
    ]
