# Generated by Django 5.0.6 on 2026-03-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.currency'),
        ),
    ]
