# Generated by Django 5.0.6 on 2026-09-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saletransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('principal', 'Company-owned (principal)'), ('agency', 'Brokered (agency)')], help_text='Blank: agency unless the property is company owned', max_length=20),
        ),
    ]
