# Generated by Django 6.0.3 on 2026-04-07 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saletransaction_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='cgt_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Capital Gains Tax', max_digits=12),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='cgt_certificate_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='occupational_rent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='rates_clearance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='rates_clearance_received',
            field=models.BooleanField(default=False),
        ),
    ]
