# Generated by Django 5.0.6 on 2026-03-10 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('finance', '0004_alter_chartofaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.currency'),
        ),
    ]
