# Generated by Django 5.0.6 on 2026-03-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_chartofaccount_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
