# Generated by Django 5.0.6 on 2026-03-11 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0006_alter_bankaccount_currency_and_more'),
        ('hr', '0001_initial'),
        ('properties', '0002_alter_property_city_alter_property_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='employee_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.employee'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='supplier_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.supplier'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['contact_ref'], name='finance_jou_contact_e24757_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['supplier_ref'], name='finance_jou_supplie_e73fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['employee_ref'], name='finance_jou_employe_265ba4_idx'),
        ),
    ]
