# Generated by Django 5.0.6 on 2026-03-12 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_chartofaccount_allow_manual_entry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='If true, this profile will be used for all system postings.')),
                ('accounts_payable', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.RESTRICT, related_name='ap_profiles', to='finance.chartofaccount')),
                ('accounts_receivable', models.ForeignKey(limit_choices_to={'account_type': 'asset'}, on_delete=django.db.models.deletion.RESTRICT, related_name='ar_profiles', to='finance.chartofaccount')),
                ('bank_main', models.ForeignKey(limit_choices_to={'account_type': 'asset'}, on_delete=django.db.models.deletion.RESTRICT, related_name='bank_main_profiles', to='finance.chartofaccount')),
                ('bank_trust', models.ForeignKey(limit_choices_to={'account_type': 'asset'}, on_delete=django.db.models.deletion.RESTRICT, related_name='bank_trust_profiles', to='finance.chartofaccount')),
                ('commission_income', models.ForeignKey(limit_choices_to={'account_type': 'revenue'}, on_delete=django.db.models.deletion.RESTRICT, related_name='comm_inc_profiles', to='finance.chartofaccount')),
                ('commission_payable', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.RESTRICT, related_name='comm_pay_profiles', to='finance.chartofaccount')),
                ('commission_receivable', models.ForeignKey(limit_choices_to={'account_type': 'asset'}, on_delete=django.db.models.deletion.RESTRICT, related_name='comm_rec_profiles', to='finance.chartofaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rental_income', models.ForeignKey(limit_choices_to={'account_type': 'revenue'}, on_delete=django.db.models.deletion.RESTRICT, related_name='rental_inc_profiles', to='finance.chartofaccount')),
                ('retained_earnings', models.ForeignKey(limit_choices_to={'account_type': 'equity'}, on_delete=django.db.models.deletion.RESTRICT, related_name='retained_profiles', to='finance.chartofaccount')),
                ('tenant_deposits', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.RESTRICT, related_name='deposit_profiles', to='finance.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vat_payable', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.RESTRICT, related_name='vat_pay_profiles', to='finance.chartofaccount')),
                ('vat_receivable', models.ForeignKey(limit_choices_to={'account_type': 'liability'}, on_delete=django.db.models.deletion.RESTRICT, related_name='vat_rec_profiles', to='finance.chartofaccount')),
            ],
            options={
                'db_table': 'finance_posting_profiles',
            },
        ),
    ]
