# Generated by Django 5.0.6 on 2026-03-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('finance', '0009_postingprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='effective_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'date')},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(db_column='currency', default='USD', on_delete=django.db.models.deletion.PROTECT, to='core.currency', to_field='code'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=6, help_text='Multiplier to convert from this currency to base currency', max_digits=18),
        ),
    ]
