# Generated by Django 5.0.6 on 2026-03-12 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_currency'),
        ('finance', '0010_alter_exchangerate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='default_currency',
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='core.currency'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_receipts', to='core.currency'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='core.currency'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='core.currency'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='core.currency'),
        ),
    ]
