# Generated by Django 5.0.6 on 2026-03-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_module_remove_role_can_approve_commissions_and_more'),
        ('finance', '0011_remove_supplier_default_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['-effective_date']},
        ),
        migrations.RenameField(
            model_name='exchangerate',
            old_name='date',
            new_name='effective_date',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'effective_date')},
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
    ]
