# Generated by Django 5.0.6 on 2026-03-12 16:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('finance', '0011_remove_supplier_default_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('exact_match', 'Exact Match (Reference + Amount)'), ('regex_match', 'Regular Expression Match'), ('keyword_match', 'Keyword Match'), ('date_amount_match', 'Date + Amount Match (within range)')], max_length=50)),
                ('match_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('match_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_tolerance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('date_tolerance_days', models.PositiveIntegerField(default=0)),
                ('auto_post', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
